In [2]:
import sys
print(sys.executable)

/opt/anaconda3/bin/python

In [4]:
import os
import pandas as pd

cred = os.path.expanduser("~/Downloads/YOUR_PROJECT-527de85df0a1.json")

file = "gs://oilnews/oil_news_000000000000.csv"

df = pd.read_csv(file, storage_options={"token": cred}, nrows=5)

print(df.head())
print(df.shape)

                 news_time                                              title  \
0  2020-01-01 00:00:00 UTC  Cause of Aberdeen oil company explosion that h...
1  2020-01-01 00:00:00 UTC        The Five Most Important Oil Stories Of 2019
2  2020-01-01 00:00:00 UTC  Cause of Aberdeen oil company explosion that h...
3  2020-01-01 00:00:00 UTC  Captain, 7 crew abducted from Greek oil tanker...
4  2020-01-01 00:00:00 UTC  Venezuela's PDVSA touts gasoline delivery to f...

                                      theme_keywords           event_type  \
0  TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...  refinery_disruption
1  WB_336_NON_BANK_FINANCIAL_INSTITUTIONS,4606;WB...         geopolitical
2  TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...  refinery_disruption
3  WOUND,1108;TAX_FNCACT_LEADERS,3378;LEADER,1539...         geopolitical
4  IDEOLOGY,2346;TAX_ETHNICITY_TIGRE,157;TAX_ETHN...         geopolitical

                                                 url
0  https://www.chron.com/news/article/Cause-of-Ab...
1  https://finance.yahoo.com/news/five-most-impor...
2  https://www.sfgate.com/news/article/Cause-of-A...
3  https://www.shanghainews.net/news/263571325/ca...
4  https://www.reuters.com/article/us-venezuela-o...
(5, 5)

In [6]:
import pandas as pd
import numpy as np
import os

cred = os.path.expanduser("~/Downloads/YOUR_PROJECT-527de85df0a1.json")

file = "gs://oilnews/oil_news_000000000000.csv"

df = pd.read_csv(file, storage_options={"token": cred})
print(df.shape)

(117449, 5)

In [8]:
df = df.dropna(subset=["title", "news_time"])
df["title"] = df["title"].astype(str).str.strip()
df = df[df["title"].str.len() >= 10]

print(df.shape)

(117449, 5)

In [10]:
df["title_clean"] = (
    df["title"]
    .str.lower()
    .str.replace(r"[^a-z0-9 ]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df = df.drop_duplicates(subset=["title_clean"])

In [12]:
df["news_time"] = pd.to_datetime(df["news_time"])
df["date"] = df["news_time"].dt.date

In [14]:
daily = df.groupby("date").size().reset_index(name="news_count")

print(daily.head())

         date  news_count
0  2020-01-01         179
1  2020-01-02         335
2  2020-01-03         996
3  2020-01-04         299
4  2020-01-05         211

In [16]:
# %%
# 1. 读取 0–8 文件
import os
import pandas as pd
import numpy as np

cred = os.path.expanduser("~/Downloads/YOUR_PROJECT-527de85df0a1.json")

files = [f"gs://oilnews/oil_news_{i:012d}.csv" for i in range(9)]

dfs = []
for f in files:
    print("读取:", f)
    temp = pd.read_csv(f, storage_options={"token": cred})
    print("shape:", temp.shape)
    dfs.append(temp)

df = pd.concat(dfs, ignore_index=True)
print("合并后大小:", df.shape)
df.head()

读取: gs://oilnews/oil_news_000000000000.csv
shape: (117449, 5)
读取: gs://oilnews/oil_news_000000000001.csv
shape: (115272, 5)
读取: gs://oilnews/oil_news_000000000002.csv
shape: (130961, 5)
读取: gs://oilnews/oil_news_000000000003.csv
shape: (106458, 5)
读取: gs://oilnews/oil_news_000000000004.csv
shape: (110567, 5)
读取: gs://oilnews/oil_news_000000000005.csv
shape: (110429, 5)
读取: gs://oilnews/oil_news_000000000006.csv
shape: (116716, 5)
读取: gs://oilnews/oil_news_000000000007.csv
shape: (153548, 5)
读取: gs://oilnews/oil_news_000000000008.csv
shape: (112121, 5)
合并后大小: (1073521, 5)

,news_time,title,theme_keywords,event_type,url
0,2020-01-01 00:00:00 UTC,Cause of Aberdeen oil company explosion that h...,"TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...",refinery_disruption,https://www.chron.com/news/article/Cause-of-Ab...
1,2020-01-01 00:00:00 UTC,The Five Most Important Oil Stories Of 2019,"WB_336_NON_BANK_FINANCIAL_INSTITUTIONS,4606;WB...",geopolitical,https://finance.yahoo.com/news/five-most-impor...
2,2020-01-01 00:00:00 UTC,Cause of Aberdeen oil company explosion that h...,"TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...",refinery_disruption,https://www.sfgate.com/news/article/Cause-of-A...
3,2020-01-01 00:00:00 UTC,"Captain, 7 crew abducted from Greek oil tanker...","WOUND,1108;TAX_FNCACT_LEADERS,3378;LEADER,1539...",geopolitical,https://www.shanghainews.net/news/263571325/ca...
4,2020-01-01 00:00:00 UTC,Venezuela's PDVSA touts gasoline delivery to f...,"IDEOLOGY,2346;TAX_ETHNICITY_TIGRE,157;TAX_ETHN...",geopolitical,https://www.reuters.com/article/us-venezuela-o...

In [18]:
# %%
# 2. 基础清洗
df = df.dropna(subset=["title", "news_time"]).copy()

df["title"] = df["title"].astype(str).str.strip()
df = df[df["title"].str.len() >= 10]

print("基础清洗后:", df.shape)
df.head()

基础清洗后: (1073521, 5)

,news_time,title,theme_keywords,event_type,url
0,2020-01-01 00:00:00 UTC,Cause of Aberdeen oil company explosion that h...,"TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...",refinery_disruption,https://www.chron.com/news/article/Cause-of-Ab...
1,2020-01-01 00:00:00 UTC,The Five Most Important Oil Stories Of 2019,"WB_336_NON_BANK_FINANCIAL_INSTITUTIONS,4606;WB...",geopolitical,https://finance.yahoo.com/news/five-most-impor...
2,2020-01-01 00:00:00 UTC,Cause of Aberdeen oil company explosion that h...,"TAX_FNCACT_DEPUTY,278;WB_2024_ANTI_CORRUPTION_...",refinery_disruption,https://www.sfgate.com/news/article/Cause-of-A...
3,2020-01-01 00:00:00 UTC,"Captain, 7 crew abducted from Greek oil tanker...","WOUND,1108;TAX_FNCACT_LEADERS,3378;LEADER,1539...",geopolitical,https://www.shanghainews.net/news/263571325/ca...
4,2020-01-01 00:00:00 UTC,Venezuela's PDVSA touts gasoline delivery to f...,"IDEOLOGY,2346;TAX_ETHNICITY_TIGRE,157;TAX_ETHN...",geopolitical,https://www.reuters.com/article/us-venezuela-o...

In [20]:
# %%
# 3. 标题标准化与去重
df["title_clean"] = (
    df["title"]
    .str.lower()
    .str.replace(r"[^a-z0-9 ]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

before = df.shape[0]
df = df.drop_duplicates(subset=["title_clean"]).copy()
after = df.shape[0]

print("去重前:", before)
print("去重后:", after)
print("去重掉:", before - after)

去重前: 1073521
去重后: 638816
去重掉: 434705

In [22]:
# %%
# 4. 时间处理：新闻时间转成 UTC，再转到市场时区
import pandas as pd
import numpy as np

market_tz = "America/New_York"

df["news_time"] = pd.to_datetime(df["news_time"], errors="coerce", utc=True)
df = df.dropna(subset=["news_time"]).copy()

# 转到纽约时区，方便和收盘时点对齐
df["news_time_local"] = df["news_time"].dt.tz_convert(market_tz)

# 排序，后面 rolling window 会用到
df = df.sort_values("news_time_local").reset_index(drop=True)

print(df[["news_time", "news_time_local"]].head())
print("新闻时间范围：", df["news_time_local"].min(), "到", df["news_time_local"].max())

                  news_time           news_time_local
0 2020-01-01 00:00:00+00:00 2019-12-31 19:00:00-05:00
1 2020-01-01 00:00:00+00:00 2019-12-31 19:00:00-05:00
2 2020-01-01 00:00:00+00:00 2019-12-31 19:00:00-05:00
3 2020-01-01 00:00:00+00:00 2019-12-31 19:00:00-05:00
4 2020-01-01 00:15:00+00:00 2019-12-31 19:15:00-05:00
新闻时间范围： 2019-12-31 19:00:00-05:00 到 2025-12-31 18:15:00-05:00

In [31]:
# %%
# 5. 读取油价（FRED: DCOILWTICO）

oil = pd.read_csv("data/oil_price.csv")

# 重命名列（方便后面统一写法）
oil = oil.rename(columns={
    "observation_date": "date",
    "DCOILWTICO": "close"
})

# 转时间
oil["date"] = pd.to_datetime(oil["date"], errors="coerce")

# 去掉缺失（FRED 周末/节假日会是 NaN）
oil = oil.dropna(subset=["date", "close"]).copy()

oil = oil.sort_values("date").reset_index(drop=True)

print(oil.head())
print("油价数据大小:", oil.shape)

        date  close
0 2020-01-02  61.17
1 2020-01-03  63.00
2 2020-01-06  63.27
3 2020-01-07  62.70
4 2020-01-08  59.65
油价数据大小: (1540, 2)

In [40]:
df.to_parquet("data/oil_news_clean.parquet", index=False)
oil.to_csv("data/oil_price_clean.csv", index=False)

In [33]:
pip install sentence-transformers

I0330 15:24:03.683358  156455 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers

Collecting sentence-transformers
  Downloading sentence_transformers-5.3.0-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.11.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (29 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.3.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub>=0.20.0->sentence-transformers)
  Downloading hf_xet-1.4.2-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.27.0)
Requirement already satisfied: packaging>=20.9 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typer in /opt/anaconda3/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.9.0)
Requirement already satisfied: setuptools<82 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence-transformers)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Collecting regex>=2025.10.22 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading regex-2026.3.32-cp312-cp312-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2024.12.14)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.2)
Requirement already satisfied: idna in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: sniffio in /opt/anaconda3/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.1.7)
Downloading sentence_transformers-5.3.0-py3-none-any.whl (512 kB)
Downloading huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 625.2/625.2 kB 14.3 MB/s eta 0:00:00
Downloading torch-2.11.0-cp312-cp312-macosx_11_0_arm64.whl (80.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 31.9 MB/s eta 0:00:0000:0100:01
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 31.9 MB/s eta 0:00:00 0:00:01
Downloading hf_xet-1.4.2-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 31.8 MB/s eta 0:00:00
Downloading regex-2026.3.32-cp312-cp312-macosx_11_0_arm64.whl (289 kB)
Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
Installing collected packages: sympy, safetensors, regex, hf-xet, torch, huggingface-hub, tokenizers, transformers, sentence-transformers
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.2
    Uninstalling sympy-1.13.2:
      Successfully uninstalled sympy-1.13.2
  Attempting uninstall: regex
    Found existing installation: regex 2024.9.11
    Uninstalling regex-2024.9.11:
      Successfully uninstalled regex-2024.9.11
Successfully installed hf-xet-1.4.2 huggingface-hub-1.8.0 regex-2026.3.32 safetensors-0.7.0 sentence-transformers-5.3.0 sympy-1.14.0 tokenizers-0.22.2 torch-2.11.0 transformers-5.4.0
Note: you may need to restart the kernel to use updated packages.

In [35]:
# %%
# 6. 标题 embedding
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

titles = df["title"].tolist()
embeddings = model.encode(
    titles,
    batch_size=64,
    show_progress_bar=True
)

print("embedding shape:", embeddings.shape)

I0330 15:24:49.331430  156455 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/9982 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
# %%
# 7. embedding 放回数据表
df = df.reset_index(drop=True)
df["embedding"] = list(embeddings)

df[["title", "date", "embedding"]].head()